version: '3.8'

services:
  mysteryforge:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./exports:/app/exports
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: mysteryforge-web
